### ISSUE TITLE
Cannot get any solvers to work with basic POMDPModels

### ISSUE THREAD

**Issue by rguptatx** [JuliaPOMDP/POMDPModels.jl#10]
I started with GridWorld and tried to use solvers such as DiscreteValueIteration and
SARSOP to find a MDP policy. I get errors with both solvers:

**with DiscreteValueIteration:**
ERROR: LoadError: POMDPs.jl: No implementation of n_states for problem::GridWorld.
 in error at ./error.jl:21
 in call at /home/.julia/v0.4/DiscreteValueIteration/src/vanilla.jl:23
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/aayush/gw.jl, in expression starting on line 368

**with SARSOP:**
ERROR: LoadError: POMDPs.jl: No implementation of create_policy for solver::SARSOP.SARSOPSolver, and problem::GridWorld.
 in error at ./error.jl:21
 in solve at no file
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/aayush/gw.jl, in expression starting on line 357

**Comment by zsunberg** [comment]
We definitely shouldn't let this kind of thing happen - Let's create some
tests that reproduce this and add them to the runtests.jl for the
appropriate packages

**Comment by rguptatx** [comment]
Test file for SARSOP solver attached.
[gw0.jl.txt](https://github.com/JuliaPOMDP/POMDPModels.jl/files/379877/gw0.jl.txt)

**Comment by rguptatx** [comment]
On the DiscreteValueIteration, please find attached 2 files:
gwNoDef.jl uses GridWorld definition from POMDPModels and works
gwWithDef.jl uses GridWorld definition copied from git src and pasted in file and has n_state errors:

[gwNoDef.jl.txt](https://github.com/JuliaPOMDP/POMDPModels.jl/files/379885/gwNoDef.jl.txt)
[gwWithDef.jl.txt](https://github.com/JuliaPOMDP/POMDPModels.jl/files/379886/gwWithDef.jl.txt)

**Comment by zsunberg** [comment]
Thanks!

**Comment by zsunberg** [comment]
Hi @rguptatx , thanks for bringing up these issues.

The reason for the SARSOP error is that SARSOP is designed to work with POMDP objects rather than MDP objects. We will add a better error message, and possibly write a little utility in the future to allow easy conversion from an MDP to a POMDP (see JuliaPOMDP/POMDPToolbox.jl#15 ).

The reason for the DiscreteValueIteration error is that, when POMDPs.jl methods are implemented in a problem definition, they must be in the POMDPs module namespace. The easiest catchall way to do this is by using `importall POMDPs` instead of `using POMDPs` in files where problems are defined (if you do this in gwWithDef, it will run without errors. See http://docs.julialang.org/en/release-0.4/manual/modules/ for more information.

Hope this helps!
