### ISSUE TITLE
"Diagonal" grid world

### ISSUE THREAD

**Issue by dominusmi** [JuliaPOMDP/POMDPModels.jl#32]
Hi everyone, for personal research, I've had to rewrite GridWorld.jl to allow for diagonal movements. It's very much a copy paste of GridWorld but with actions set as _n,nw,w,sw,s,se,e,ne_ (north, north-west, west, ..) and all the various constants and functions adapted. 

I was wondering if this was something that you would be interested in merging, or whether I just keep it on my own repository. 

In the case you're interested, I would also suggest creating an abstract type, `GridWorld`, of which `DiagGridWorld` and `SimpleGridWorld`  would be subtypes (or something around those lines), allowing users to define generic grid world functions.

**Comment by zsunberg** [comment]
Hey @dominusmi , Thanks for reaching out!

The grid world use case is actually so common that I think we should eventually make another package called GridWorlds.jl that has an extensible base gridworld model in it. My advisor teaches a class at Stanford every year (https://web.stanford.edu/class/aa228/cgi-bin/wp/), and many students use grid world derivatives for their projects. What would be awesome is if we could make a composable grid world system, so that people could take the basic grid world model and use their own action space, give attributes to grid locations, etc. 

I think that the models in POMDPModels should be optimized for code clarity and conciseness (while avoiding major performance issues). In fact, I think we should put some effort in to change the current GridWorld model to optimize for code conciseness - I am always quite embarassed to show the current version to people :/.

If we are optimizing for that, I don't think we should have multiple versions of it; they should go in other packages.

@MaximeBouton , @rejuvyesh , @Shushman , @mykelk , do you have any thoughts on what we should optimize for in POMDPModels and whether we should have multiple GridWorld models in the POMDPModels package?

@dominusmi can you share a link to your package? We should definitely have a way for people to find things like this.

**Comment by mykelk** [comment]
I think we can have multiple GridWorld models so long as there are fewer than seven.

**Comment by Shushman** [comment]
I do like the idea of a composable grid world - the common aspects would be the fact that it is a rectangular grid with individual cells and a goal cell, and that a state is a cell, but then the kinds of movements, cell attributes etc as Zach mentioned, could all be modified as per the user's wish (We could provide a couple of default types maybe?) That would both be concise (by being composable) and be more clear I think?

**Comment by rejuvyesh** [comment]
Also see https://github.com/deepmind/pycolab

**Comment by dominusmi** [comment]
I definitely agree with the composable type, and making a GridWorlds.jl package would be (I think) the best way to go about it. 
My code can be found here: https://github.com/dominusmi/POMDPModels.jl/blob/master/src/DiagGridWorlds.jl
As I said, I didn't change anything excepting adding the extra diagonal movements, I just needed it so didn't bother with the extra abstraction types, so I modified the source directly and created a new type for 
personal use.

If you decide to go on trying to make this GridWorlds.jl package, I'd happily contribute!

**Comment by zsunberg** [comment]
Cool, yeah, I don't think any one of us here in sisl has the bandwidth to take leadership of that package right now, but it would be a good thing eventually. If someone does it before the middle of october, I bet a ton of people would use it in AA228

btw here is a sketch of a more concise gridworld: https://gist.github.com/zsunberg/50518f90dff071ca830cfb1e46380164

**Comment by dominusmi** [comment]
As follow up to this, I've made a separate package, [GridWorlds.jl](https://github.com/dominusmi/GridWorlds.jl). 
Collaboration (even under the form of advice or features of interest) is highly welcome.
